config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'groups#index'
  resources :groups do
    resources :messages
  end
  resources :users, only: :index
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :users, through: :group_users
  has_many :messages

  validates :name, :user_ids, presence: true
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :group
  belongs_to :user

  validates :group, :user, presence: true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :group
  validates :group, :user, presence: true
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :name
  has_many :group_users
  has_many :groups, through: :group_users
  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameter, if: :devise_controller?

  protected

  def configure_permitted_parameter
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  def after_sign_out_path_for(resource)
    new_user_session_path
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!, only: :index
  before_action :set_group, only: [:edit, :update]

  def index
    @groups = current_user.groups
  end

  def new
    @group = Group.new
    @group.users << current_user
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to group_messages_path(@group), notice: t('.notice')
    else
      flash.now[:alert] = t('.alert')
      render :new
    end
  end

  def edit
  end

  def update
    if @group.update(group_params)
      redirect_to group_messages_path(@group), notice: t('.notice')
    else
      flash.now[:alert] = t('.alert')
      render :edit
    end
  end

  private
  def set_group
    @group = Group.find(params[:id])
  end

  def group_params
    params.require(:group).permit(:name, user_ids: [])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!, only: :index
  before_action :set_group, only: [:index, :create]

  def index
    @message = Message.new
    respond_to do |format|
      format.html { render :index }
      format.json { render json: @group.messages, include: :user }
    end
  end

  def create
    @message = @group.messages.build(message_params)
    respond_to do |format|
      if @message.save
        format.html do
          redirect_to group_messages_path(@group)
        end
        format.json do
          render json: @message, include: :user
        end
      else
        format.html do
          redirect_to group_messages_path(@group), alert: t('.alert')
        end
        format.json do
          render json: @message.errors, status: :unprocessable_entity
        end
      end
    end
  end

  private
  def set_group
    @group = Group.find(params[:group_id])
  end

  def message_params
    params.require(:message).permit(:body, :image).merge(user_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.where('name LIKE?', "%#{params[:keyword]}%")
    respond_to do |format|
      format.json { render json: @users }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/_navigation.html.haml
.navbar-left.left
  .navbar-left__user
    %p.left chat-ojisan
    .items.right
      = link_to new_group_path, class: 'icon-btn' do
        %i.fa.fa-pencil-square-o
      = link_to edit_user_registration_path, class: 'icon-btn' do
        %i.fa.fa-cog
  .navbar-left__groups
    %ul
      - current_user.groups.each do |group|
        %li.list-group
          = link_to group_messages_path(group) do
            %p.list-group__name
              = group.name
            %p.list-group__message
              aaaaaaaaaaaaa

app/views/groups/edit.html.haml
.chat-group-form
  %h1 チャットグループ編集
  = form_for @group, method: :patch do |f|
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        = f.label :name, "グループ名", class: "chat-group-form__label"
      .chat-group-form__field--right
        = f.text_field :name, class: "chat-group-form__input", id: "chat_group_name", placeholder: "グループ名を入力してください"
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        = f.label 'チャットメンバーを追加', class: 'chat-group-form__label'
      .chat-group-form__field--right
        .chat-group-form__search.clearfix
          %input#user-search-field.chat-group-form__input{:placeholder => "追加したいユーザー名を入力してください", :type => "text"}/
        #user-search-result
    .chat-group-form__field
      .chat-group-form__field--left
        = f.label "チャットメンバー", class: 'chat-group-form__label'
      .chat-group-form__field--right
        #chat-group-users
          - @group.users.each do |user|
            .chat-group-user.clearfix{id: "chat-group-user-#{user.id}"}
              %input{ name: "group[user_ids][]", type: "hidden", value: "#{user.id}" }
              %p{ class: "chat-group-user__name" }
                = user.name
              - unless current_user === user
                %a{ class: "user-search-remove chat-group-user__btn chat-group-user__btn--remove", 'data-user-id' => user.id } 削除
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
      .chat-group-form__field--right
        = f.submit "Save", class: 'chat-group-form__action-btn', 'data-disable-with' => 'Save'

app/views/groups/index.html.haml
.chatspace.clearfix
  = render 'navigation'

app/views/groups/new.html.haml
.chat-group-form
  %h1 新規チャットグループ
  = form_for @group do |f|
    .chat-group-form__field
      .chat-group-form__field--left
        = f.label :name, 'グループ名', class: 'chat-group-form__label'
      .chat-group-form__field--right
        = f.text_field :name, class: 'chat-group-form__input', id: 'chat_group_name', placeholder: 'グループ名を入力してください'
    .chat-group-form__field
      .chat-group-form__field--left
        = f.label 'チャットメンバーを追加', class: 'chat-group-form__label'
      .chat-group-form__field--right
        .chat-group-form__search.clearfix
          %input#user-search-field.chat-group-form__input{:placeholder => "追加したいユーザー名を入力してください", :type => "text"}/
        #user-search-result
    .chat-group-form__field
      .chat-group-form__field--left
        = f.label "チャットメンバー", class: 'chat-group-form__label'
      .chat-group-form__field--right
        #chat-group-users
          .chat-group-user.clearfix{id: "chat-group-user-#{current_user.id}"}
            %input{ name: "group[user_ids][]", type: "hidden", value: "#{current_user.id}" }
            %p{ class: "chat-group-user__name" }
              = current_user.name
    .chat-group-form__field
      .chat-group-form__field--left
      .chat-group-form__field--right
        = f.submit "Save", class: 'chat-group-form__action-btn', 'data-disable-with' => 'Save'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ChatSpace
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    -if notice
      %p.layout-notice
        = notice
    -if alert
      %p.layout-alert
        = alert
    .layout-notification
      = yield

app/views/messages/index.haml
.chatspace.clearfix
  = render 'groups/navigation'
  .chat.left
    .chat-header
      .chat-header__left.left
        %p.group-name
          %h2
            = @group.name
        .chat-header__left__members
          %p
            Members:
            - @group.users.each do |user|
              = user.name

      .chat-header__right.right
        = link_to 'Edit', edit_group_path(@group), class: "edit-btn"
    .chat-body
      %ul.chat-info
        - @group.messages.each do |message|
          %li
            .list-header
              .list-header__name.left
                = message.user.name
              .list-header__date.left
                = l(message.created_at)
            .list-message
              = message.body
              %br
              = image_tag(message.image.thumb)
    .chat-footer
      = form_for [@group, @message], html: { class: "relative" } do |f|
        .footer-body.relative
          = f.text_area :body, class: "message_body", placeholder: "type a message"
          = f.label "", class: "footer-file absolute-top-right", for: "message_image" do
            = f.file_field :image, id: "message_image"
            %i.fa.fa-image
        = f.submit "Send", class: "submit-btn absolute-top-right"